spring:
  datasource:
    name: Montessori DB MySQL connection
    url: jdbc:mysql://localhost:3306/MontessoriSchool?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true&useUnicode=true
    username: root
    password: jovan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update  # Automatically create or update tables based on entities


# TODO: implement caching
#    properties:
#      hibernate:
#        format_sql: true
#        cache: # we enable caching mechanism (2nd level cache)
#          use_second_level_cache: true
#          use_query_cache: true
#          region:
#            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
#        javax:
#          cache:
#            provider: "org.ehcache.jsr107.EhcacheCachingProvider"
#            missing_cache_strategy: create

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

server:
  port: 8080