spring:
  application:
    name: Montessori School

  # active profile when app is running
  profiles:
    active: dev

# to configure aws s3 bucket for image storage
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: dedis

  # maximum allowed size of image per upload
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  # email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: jovanvukovic09@gmail.com
    password: ctrnwzthugudhizm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server: # admins session will last 20 minute once he is logged in
  servlet:
    session:
      timeout: 20m

# TODO: check if needed when deploying on render.
#spring.application.name=dedis
#server.tomcat.max-threads=50  # Lower default is 200
#server.tomcat.min-spare-threads=10  # Lower default is 10