version: '3.2'

services:

  # MySQL Database
  mysql:
    image: mysql:9.1.0
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jovan
      TZ: 'Europe/Belgrade'
    volumes:
      - ./data/db-config/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./data/db-log:/var/log/mysql
      - ./data/db-init:/docker-entrypoint-initdb.d
      - ./data/db-files:/var/lib/mysql-files
      - ./data/db-data:/var/lib/mysql
      - /var/run/mysqld/:/var/run/mysqld
    command: mysqld --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;'
    restart: always
    container_name: db9
    networks:
      - mynet

  # Java APP (Spring Boot)
  backend-srv:
    build:
      dockerfile: Dockerfile
    image: jovanvukovicc/dedis111:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./conf:/config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      #SPRING_DATASOURCE_URL: jdbc:mysql://db9:3306/academy_db
      # SPRING_DATASOURCE_USERNAME: root
      #SPRING_DATASOURCE_PASSWORD: jovan
    restart: on-failure
    container_name: backend-srv
    networks:
      - mynet

networks:
  mynet: